name: Deploy to EC2

on:
  push:
    branches:
      - master  # 또는 main, 네 저장소 기본 브랜치에 맞춰!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 52.79.107.223                # ← 너의 EC2 퍼블릭 IP
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/my-project                  # ← EC2에 네 코드가 있는 폴더
          git pull origin master           # 또는 main
          npm install
          pm2 restart app
