name: Deploy to EC2

on:
  push:
    branches:
      - master  # ← 네 브랜치가 main이면 main으로 바꿔줘!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 52.79.107.223
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/my-project
          git pull origin master
          ~/.nvm/versions/node/v24.0.2/bin/npm install
          ~/.nvm/versions/node/v24.0.2/bin/pm2 restart app
